version: '2'
services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
    environment:
        POSTGRES_DB: release_notes
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOSTNAME: db
        POSTGRES_HOST_AUTH_METHOD: trust
  app:
    build:
      dockerfile: ./docker/dev/Dockerfile
      context: ./
    environment:
        MIX_ENV: dev
        SECRET_KEY_BASE: secret
        DATABASE_URL: postgres://postgres:password@db/release_notes
        POSTGRES_DB: release_notes
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOSTNAME: db
        PORT: 4002
    ports:
      - "4002:4002"
    volumes:
      - ".:/app"
    depends_on:
      - db

