version: '2'
services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
    environment:
        POSTGRES_DB: release_notes
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOSTNAME: db
  app:
    build:
      dockerfile: ./docker/dev/Dockerfile
      context: ./
    env_file: .env
    environment:
        MIX_ENV: dev
        SECRET_KEY_BASE: secret
    ports:
      - "4002:4002"
    volumes:
      - ".:/app"
    depends_on:
      - db

