name: Fly Deploy Staging
on:
  pull_request:
    branches:
      - main
    types: [closed]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      if: ${{ github.event.pull_request.merged }}
      name: Deploy app to fly staging
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: cp fly.toml.staging fly.toml
        - run: flyctl deploy --remote-only
